# Generated by Django 5.1.4 on 2024-12-31 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='topping',
            name='additional_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
